Feature/id-08/job-implementation-post
sistemasweb5/JobService pull request #4
Opened 2024-10-28 17:09 UTC by axel-ayala-jalafund

Here is implemented POST implementation with GraphQL.

- Here is link of US on trello: [Job Implementation Post](https://trello.com/c/fSVza2sF/10-id-08-job-implementation-post)

2024-10-28 21:53 UTC, luiggy-mamani-jalafund requested changes
I have been testing from the frontend, and I had a CORS problem, can you fix that please:

![image](https://github.com/user-attachments/assets/819bbea9-5538-4607-aee6-32da22a71037)

2024-10-28 23:38 UTC, luiggy-mamani-jalafund approved these changes

2024-10-29 00:03 UTC, JosuePrado approved these changes

2024-10-29 01:47 UTC, alex-paca-jalafund approved these changes

2024-10-29 01:47 UTC, merged